; CSA_Z243.4-1985-GR UCS-2 encoding rule
; source:  ftp://dkuug.dk/i18n/charmaps/CSA_Z243.4-1985-GR
any [
#{A2} (insert tail result #{00A8}) | 
#{A4} (insert tail result #{00A2}) | 
#{A6} (insert tail result #{00B1}) | 
#{A7} (insert tail result #{00B4}) | 
#{A8} (insert tail result #{207D}) | 
#{A9} (insert tail result #{207E}) | 
#{AA} (insert tail result #{00BD}) | 
#{AB} (insert tail result #{207A}) | 
#{AC} (insert tail result #{00B8}) | 
#{AE} (insert tail result #{00B7}) | 
#{AF} (insert tail result #{207B}) | 
#{B0} (insert tail result #{2070}) | 
#{B1} (insert tail result #{00B9}) | 
#{B4} (insert tail result #{2074}) | 
#{B5} (insert tail result #{2075}) | 
#{B6} (insert tail result #{2076}) | 
#{B7} (insert tail result #{2077}) | 
#{B8} (insert tail result #{2078}) | 
#{B9} (insert tail result #{2079}) | 
#{BA} (insert tail result #{00BC}) | 
#{BB} (insert tail result #{00BE}) | 
#{BC} (insert tail result #{21D0}) | 
#{BD} (insert tail result #{2260}) | 
#{BE} (insert tail result #{2265}) | 
#{C3} (insert tail result #{00C7}) | 
#{C4} (insert tail result #{00C8}) | 
#{C5} (insert tail result #{00C9}) | 
#{C6} (insert tail result #{00CA}) | 
#{C7} (insert tail result #{00CB}) | 
#{C8} (insert tail result #{00CD}) | 
#{C9} (insert tail result #{00CE}) | 
#{CA} (insert tail result #{00CF}) | 
#{CB} (insert tail result #{00D1}) | 
#{CC} (insert tail result #{00D3}) | 
#{CD} (insert tail result #{00D4}) | 
#{CE} (insert tail result #{00D9}) | 
#{CF} (insert tail result #{00DA}) | 
#{D0} (insert tail result #{00DB}) | 
#{D1} (insert tail result #{00DC}) | 
#{D2} (insert tail result #{00AE}) | 
#{D3} (insert tail result #{00A7}) | 
#{D4} (insert tail result #{00B6}) | 
#{D5} (insert tail result #{00B5}) | 
#{D6} (insert tail result #{00AA}) | 
#{D7} (insert tail result #{00BA}) | 
#{D8} (insert tail result #{2018}) | 
#{D9} (insert tail result #{2019}) | 
#{DA} (insert tail result #{201C}) | 
#{DB} (insert tail result #{201D}) | 
#{DC} (insert tail result #{00AB}) | 
#{DD} (insert tail result #{00BB}) | 
#{DE} (insert tail result #{00B0}) | 
#{DF} (insert tail result #{00A6}) | 
#{E3} (insert tail result #{00E7}) | 
#{E4} (insert tail result #{00E8}) | 
#{E5} (insert tail result #{00E9}) | 
#{E6} (insert tail result #{00EA}) | 
#{E7} (insert tail result #{00EB}) | 
#{E8} (insert tail result #{00ED}) | 
#{E9} (insert tail result #{00EE}) | 
#{EA} (insert tail result #{00EF}) | 
#{EB} (insert tail result #{00F1}) | 
#{EC} (insert tail result #{00F3}) | 
#{ED} (insert tail result #{00F4}) | 
#{EE} (insert tail result #{00F9}) | 
#{EF} (insert tail result #{00FA}) | 
#{F0} (insert tail result #{00FB}) | 
#{F1} (insert tail result #{00FC}) | 
#{F2} (insert tail result #{00A9}) | 
#{F3} (insert tail result #{2500}) | 
#{F4} (insert tail result #{2502}) | 
#{F5} (insert tail result #{2514}) | 
#{F6} (insert tail result #{2518}) | 
#{F7} (insert tail result #{2510}) | 
#{F8} (insert tail result #{250C}) | 
#{F9} (insert tail result #{251C}) | 
#{FA} (insert tail result #{2534}) | 
#{FB} (insert tail result #{2524}) | 
#{FC} (insert tail result #{252C}) | 
#{FD} (insert tail result #{253C}) | 
#{FE} (insert tail result #{00AC}) | 
#{FF} (insert tail result #{2588}) | 
copy c 1 skip (insert tail result join #{00} c)
]