; HP-ROMAN8 UCS-2 encoding rule
; source:  ftp://dkuug.dk/i18n/charmaps/HP-ROMAN8
any [
#{A1} (insert tail result #{00C0}) | 
#{A2} (insert tail result #{00C2}) | 
#{A3} (insert tail result #{00C8}) | 
#{A4} (insert tail result #{00CA}) | 
#{A5} (insert tail result #{00CB}) | 
#{A6} (insert tail result #{00CE}) | 
#{A7} (insert tail result #{00CF}) | 
#{A8} (insert tail result #{00B4}) | 
#{A9} (insert tail result #{02CB}) | 
#{AA} (insert tail result #{02C6}) | 
#{AB} (insert tail result #{00A8}) | 
#{AC} (insert tail result #{02DC}) | 
#{AD} (insert tail result #{00D9}) | 
#{AE} (insert tail result #{00DB}) | 
#{AF} (insert tail result #{20A4}) | 
#{B0} (insert tail result #{00AF}) | 
#{B1} (insert tail result #{00DD}) | 
#{B2} (insert tail result #{00FD}) | 
#{B3} (insert tail result #{00B0}) | 
#{B4} (insert tail result #{00C7}) | 
#{B5} (insert tail result #{00E7}) | 
#{B6} (insert tail result #{00D1}) | 
#{B7} (insert tail result #{00F1}) | 
#{B8} (insert tail result #{00A1}) | 
#{B9} (insert tail result #{00BF}) | 
#{BA} (insert tail result #{00A4}) | 
#{BB} (insert tail result #{00A3}) | 
#{BC} (insert tail result #{00A5}) | 
#{BD} (insert tail result #{00A7}) | 
#{BE} (insert tail result #{0192}) | 
#{BF} (insert tail result #{00A2}) | 
#{C0} (insert tail result #{00E2}) | 
#{C1} (insert tail result #{00EA}) | 
#{C2} (insert tail result #{00F4}) | 
#{C3} (insert tail result #{00FB}) | 
#{C4} (insert tail result #{00E1}) | 
#{C5} (insert tail result #{00E9}) | 
#{C6} (insert tail result #{00F3}) | 
#{C7} (insert tail result #{00FA}) | 
#{C8} (insert tail result #{00E0}) | 
#{C9} (insert tail result #{00E8}) | 
#{CA} (insert tail result #{00F2}) | 
#{CB} (insert tail result #{00F9}) | 
#{CC} (insert tail result #{00E4}) | 
#{CD} (insert tail result #{00EB}) | 
#{CE} (insert tail result #{00F6}) | 
#{CF} (insert tail result #{00FC}) | 
#{D0} (insert tail result #{00C5}) | 
#{D1} (insert tail result #{00EE}) | 
#{D2} (insert tail result #{00D8}) | 
#{D3} (insert tail result #{00C6}) | 
#{D4} (insert tail result #{00E5}) | 
#{D5} (insert tail result #{00ED}) | 
#{D6} (insert tail result #{00F8}) | 
#{D7} (insert tail result #{00E6}) | 
#{D8} (insert tail result #{00C4}) | 
#{D9} (insert tail result #{00EC}) | 
#{DA} (insert tail result #{00D6}) | 
#{DB} (insert tail result #{00DC}) | 
#{DC} (insert tail result #{00C9}) | 
#{DD} (insert tail result #{00EF}) | 
#{DE} (insert tail result #{00DF}) | 
#{DF} (insert tail result #{00D4}) | 
#{E0} (insert tail result #{00C1}) | 
#{E1} (insert tail result #{00C3}) | 
#{E2} (insert tail result #{00E3}) | 
#{E3} (insert tail result #{00D0}) | 
#{E4} (insert tail result #{00F0}) | 
#{E5} (insert tail result #{00CD}) | 
#{E6} (insert tail result #{00CC}) | 
#{E7} (insert tail result #{00D3}) | 
#{E8} (insert tail result #{00D2}) | 
#{E9} (insert tail result #{00D5}) | 
#{EA} (insert tail result #{00F5}) | 
#{EB} (insert tail result #{0160}) | 
#{EC} (insert tail result #{0161}) | 
#{ED} (insert tail result #{00DA}) | 
#{EE} (insert tail result #{0178}) | 
#{EF} (insert tail result #{00FF}) | 
#{F0} (insert tail result #{00DE}) | 
#{F1} (insert tail result #{00FE}) | 
#{F2} (insert tail result #{00B7}) | 
#{F3} (insert tail result #{00B5}) | 
#{F4} (insert tail result #{00B6}) | 
#{F5} (insert tail result #{00BE}) | 
#{F6} (insert tail result #{2014}) | 
#{F7} (insert tail result #{00BC}) | 
#{F8} (insert tail result #{00BD}) | 
#{F9} (insert tail result #{00AA}) | 
#{FA} (insert tail result #{00BA}) | 
#{FB} (insert tail result #{00AB}) | 
#{FC} (insert tail result #{25A0}) | 
#{FD} (insert tail result #{00BB}) | 
#{FE} (insert tail result #{00B1}) | 
copy c 1 skip (insert tail result join #{00} c)
]