; IBM864 UCS-2 decoding rule
;  source: ftp://dkuug.dk/i18n/charmaps/IBM864
any [
#{00B0} (insert tail result #{80}) | 
#{00B7} (insert tail result #{81}) | 
#{2218} (insert tail result #{82}) | 
#{221A} (insert tail result #{83}) | 
#{2592} (insert tail result #{84}) | 
#{2500} (insert tail result #{85}) | 
#{2502} (insert tail result #{86}) | 
#{253C} (insert tail result #{87}) | 
#{2524} (insert tail result #{88}) | 
#{252C} (insert tail result #{89}) | 
#{251C} (insert tail result #{8A}) | 
#{2534} (insert tail result #{8B}) | 
#{2510} (insert tail result #{8C}) | 
#{250C} (insert tail result #{8D}) | 
#{2514} (insert tail result #{8E}) | 
#{2518} (insert tail result #{8F}) | 
#{00DF} (insert tail result #{90}) | 
#{221E} (insert tail result #{91}) | 
#{00F8} (insert tail result #{92}) | 
#{00B1} (insert tail result #{93}) | 
#{00BD} (insert tail result #{94}) | 
#{00BC} (insert tail result #{95}) | 
#{2248} (insert tail result #{96}) | 
#{00AB} (insert tail result #{97}) | 
#{00BB} (insert tail result #{98}) | 
#{FEF7} (insert tail result #{99}) | 
#{FEF8} (insert tail result #{9A}) | 
#{FEFB} (insert tail result #{9D}) | 
#{FEFC} (insert tail result #{9E}) | 
#{E016} (insert tail result #{9F}) | 
#{00AD} (insert tail result #{A1}) | 
#{FE82} (insert tail result #{A2}) | 
#{FE84} (insert tail result #{A5}) | 
#{FE8E} (insert tail result #{A8}) | 
#{0628} (insert tail result #{A9}) | 
#{062A} (insert tail result #{AA}) | 
#{062B} (insert tail result #{AB}) | 
#{060C} (insert tail result #{AC}) | 
#{062C} (insert tail result #{AD}) | 
#{062D} (insert tail result #{AE}) | 
#{062E} (insert tail result #{AF}) | 
#{0660} (insert tail result #{B0}) | 
#{0661} (insert tail result #{B1}) | 
#{0662} (insert tail result #{B2}) | 
#{0663} (insert tail result #{B3}) | 
#{0664} (insert tail result #{B4}) | 
#{0665} (insert tail result #{B5}) | 
#{0666} (insert tail result #{B6}) | 
#{0667} (insert tail result #{B7}) | 
#{0668} (insert tail result #{B8}) | 
#{0669} (insert tail result #{B9}) | 
#{06A4} (insert tail result #{BA}) | 
#{061B} (insert tail result #{BB}) | 
#{0633} (insert tail result #{BC}) | 
#{0634} (insert tail result #{BD}) | 
#{0635} (insert tail result #{BE}) | 
#{061F} (insert tail result #{BF}) | 
#{00A2} (insert tail result #{C0}) | 
#{0621} (insert tail result #{C1}) | 
#{0622} (insert tail result #{C2}) | 
#{0623} (insert tail result #{C3}) | 
#{0624} (insert tail result #{C4}) | 
#{FECA} (insert tail result #{C5}) | 
#{0626} (insert tail result #{C6}) | 
#{0627} (insert tail result #{C7}) | 
#{FE91} (insert tail result #{C8}) | 
#{0629} (insert tail result #{C9}) | 
#{FE97} (insert tail result #{CA}) | 
#{FE9B} (insert tail result #{CB}) | 
#{FE9F} (insert tail result #{CC}) | 
#{FEA3} (insert tail result #{CD}) | 
#{FEA7} (insert tail result #{CE}) | 
#{062F} (insert tail result #{CF}) | 
#{0630} (insert tail result #{D0}) | 
#{0631} (insert tail result #{D1}) | 
#{0632} (insert tail result #{D2}) | 
#{FEB3} (insert tail result #{D3}) | 
#{FEB7} (insert tail result #{D4}) | 
#{FEBB} (insert tail result #{D5}) | 
#{FEBF} (insert tail result #{D6}) | 
#{0637} (insert tail result #{D7}) | 
#{0638} (insert tail result #{D8}) | 
#{FECB} (insert tail result #{D9}) | 
#{FECF} (insert tail result #{DA}) | 
#{00A6} (insert tail result #{DB}) | 
#{00AC} (insert tail result #{DC}) | 
#{00F7} (insert tail result #{DD}) | 
#{00D7} (insert tail result #{DE}) | 
#{0639} (insert tail result #{DF}) | 
#{0640} (insert tail result #{E0}) | 
#{FED2} (insert tail result #{E1}) | 
#{FED6} (insert tail result #{E2}) | 
#{FEDB} (insert tail result #{E3}) | 
#{FEDE} (insert tail result #{E4}) | 
#{FEE3} (insert tail result #{E5}) | 
#{FEEB} (insert tail result #{E7}) | 
#{0648} (insert tail result #{E8}) | 
#{0649} (insert tail result #{E9}) | 
#{FEF3} (insert tail result #{EA}) | 
#{0636} (insert tail result #{EB}) | 
#{FEE2} (insert tail result #{EC}) | 
#{FECE} (insert tail result #{ED}) | 
#{063A} (insert tail result #{EE}) | 
#{0645} (insert tail result #{EF}) | 
#{FE7D} (insert tail result #{F0}) | 
#{0651} (insert tail result #{F1}) | 
#{0646} (insert tail result #{F2}) | 
#{0647} (insert tail result #{F3}) | 
#{FEEC} (insert tail result #{F4}) | 
#{FEF0} (insert tail result #{F5}) | 
#{FEF2} (insert tail result #{F6}) | 
#{0641} (insert tail result #{F7}) | 
#{0642} (insert tail result #{F8}) | 
#{FEF5} (insert tail result #{F9}) | 
#{FEF6} (insert tail result #{FA}) | 
#{0644} (insert tail result #{FB}) | 
#{0643} (insert tail result #{FC}) | 
#{064A} (insert tail result #{FD}) | 
#{25A0} (insert tail result #{FE}) | 
#{00A0} (insert tail result #{FF}) | 
#{00} copy c 1 skip (insert tail result c) | 
copy c 2 skip (decodeUnknownChar c)
]