; ISO-8859-7 UCS-2 encoding rule
; source:  ftp://dkuug.dk/i18n/charmaps/ISO-8859-7
any [
#{A1} (insert tail result #{2018}) | 
#{A2} (insert tail result #{2019}) | 
#{AF} (insert tail result #{2014}) | 
#{B5} (insert tail result #{0385}) | 
#{B6} (insert tail result #{0386}) | 
#{B8} (insert tail result #{0388}) | 
#{B9} (insert tail result #{0389}) | 
#{BA} (insert tail result #{038A}) | 
#{BC} (insert tail result #{038C}) | 
#{BE} (insert tail result #{038E}) | 
#{BF} (insert tail result #{038F}) | 
#{C0} (insert tail result #{0390}) | 
#{C1} (insert tail result #{0391}) | 
#{C2} (insert tail result #{0392}) | 
#{C3} (insert tail result #{0393}) | 
#{C4} (insert tail result #{0394}) | 
#{C5} (insert tail result #{0395}) | 
#{C6} (insert tail result #{0396}) | 
#{C7} (insert tail result #{0397}) | 
#{C8} (insert tail result #{0398}) | 
#{C9} (insert tail result #{0399}) | 
#{CA} (insert tail result #{039A}) | 
#{CB} (insert tail result #{039B}) | 
#{CC} (insert tail result #{039C}) | 
#{CD} (insert tail result #{039D}) | 
#{CE} (insert tail result #{039E}) | 
#{CF} (insert tail result #{039F}) | 
#{D0} (insert tail result #{03A0}) | 
#{D1} (insert tail result #{03A1}) | 
#{D3} (insert tail result #{03A3}) | 
#{D4} (insert tail result #{03A4}) | 
#{D5} (insert tail result #{03A5}) | 
#{D6} (insert tail result #{03A6}) | 
#{D7} (insert tail result #{03A7}) | 
#{D8} (insert tail result #{03A8}) | 
#{D9} (insert tail result #{03A9}) | 
#{DA} (insert tail result #{03AA}) | 
#{DB} (insert tail result #{03AB}) | 
#{DC} (insert tail result #{03AC}) | 
#{DD} (insert tail result #{03AD}) | 
#{DE} (insert tail result #{03AE}) | 
#{DF} (insert tail result #{03AF}) | 
#{E0} (insert tail result #{03B0}) | 
#{E1} (insert tail result #{03B1}) | 
#{E2} (insert tail result #{03B2}) | 
#{E3} (insert tail result #{03B3}) | 
#{E4} (insert tail result #{03B4}) | 
#{E5} (insert tail result #{03B5}) | 
#{E6} (insert tail result #{03B6}) | 
#{E7} (insert tail result #{03B7}) | 
#{E8} (insert tail result #{03B8}) | 
#{E9} (insert tail result #{03B9}) | 
#{EA} (insert tail result #{03BA}) | 
#{EB} (insert tail result #{03BB}) | 
#{EC} (insert tail result #{03BC}) | 
#{ED} (insert tail result #{03BD}) | 
#{EE} (insert tail result #{03BE}) | 
#{EF} (insert tail result #{03BF}) | 
#{F0} (insert tail result #{03C0}) | 
#{F1} (insert tail result #{03C1}) | 
#{F2} (insert tail result #{03C2}) | 
#{F3} (insert tail result #{03C3}) | 
#{F4} (insert tail result #{03C4}) | 
#{F5} (insert tail result #{03C5}) | 
#{F6} (insert tail result #{03C6}) | 
#{F7} (insert tail result #{03C7}) | 
#{F8} (insert tail result #{03C8}) | 
#{F9} (insert tail result #{03C9}) | 
#{FA} (insert tail result #{03CA}) | 
#{FB} (insert tail result #{03CB}) | 
#{FC} (insert tail result #{03CC}) | 
#{FD} (insert tail result #{03CD}) | 
#{FE} (insert tail result #{03CE}) | 
copy c 1 skip (insert tail result join #{00} c)
]