; JIS_X0201 UCS-2 decoding rule
;  source: ftp://dkuug.dk/i18n/charmaps/JIS_X0201
any [
#{00A5} (insert tail result #{5C}) | 
#{203E} (insert tail result #{7E}) | 
#{3002} (insert tail result #{A1}) | 
#{300C} (insert tail result #{A2}) | 
#{300D} (insert tail result #{A3}) | 
#{3001} (insert tail result #{A4}) | 
#{30FB} (insert tail result #{A5}) | 
#{30F2} (insert tail result #{A6}) | 
#{30A1} (insert tail result #{A7}) | 
#{30A3} (insert tail result #{A8}) | 
#{30A5} (insert tail result #{A9}) | 
#{30A7} (insert tail result #{AA}) | 
#{30A9} (insert tail result #{AB}) | 
#{30E3} (insert tail result #{AC}) | 
#{30E5} (insert tail result #{AD}) | 
#{30E7} (insert tail result #{AE}) | 
#{30C3} (insert tail result #{AF}) | 
#{30FC} (insert tail result #{B0}) | 
#{30A2} (insert tail result #{B1}) | 
#{30A4} (insert tail result #{B2}) | 
#{30A6} (insert tail result #{B3}) | 
#{30A8} (insert tail result #{B4}) | 
#{30AA} (insert tail result #{B5}) | 
#{30AB} (insert tail result #{B6}) | 
#{30AD} (insert tail result #{B7}) | 
#{30AF} (insert tail result #{B8}) | 
#{30B1} (insert tail result #{B9}) | 
#{30B3} (insert tail result #{BA}) | 
#{30B5} (insert tail result #{BB}) | 
#{30B7} (insert tail result #{BC}) | 
#{30B9} (insert tail result #{BD}) | 
#{30BB} (insert tail result #{BE}) | 
#{30BD} (insert tail result #{BF}) | 
#{30BF} (insert tail result #{C0}) | 
#{30C4} (insert tail result #{C2}) | 
#{30C6} (insert tail result #{C3}) | 
#{30C8} (insert tail result #{C4}) | 
#{30CA} (insert tail result #{C5}) | 
#{30CB} (insert tail result #{C6}) | 
#{30CC} (insert tail result #{C7}) | 
#{30CD} (insert tail result #{C8}) | 
#{30CE} (insert tail result #{C9}) | 
#{30CF} (insert tail result #{CA}) | 
#{30D2} (insert tail result #{CB}) | 
#{30D5} (insert tail result #{CC}) | 
#{30D8} (insert tail result #{CD}) | 
#{30DB} (insert tail result #{CE}) | 
#{30DE} (insert tail result #{CF}) | 
#{30DF} (insert tail result #{D0}) | 
#{30E0} (insert tail result #{D1}) | 
#{30E1} (insert tail result #{D2}) | 
#{30E2} (insert tail result #{D3}) | 
#{30E4} (insert tail result #{D4}) | 
#{30E6} (insert tail result #{D5}) | 
#{30E8} (insert tail result #{D6}) | 
#{30E9} (insert tail result #{D7}) | 
#{30EA} (insert tail result #{D8}) | 
#{30EB} (insert tail result #{D9}) | 
#{30EC} (insert tail result #{DA}) | 
#{30ED} (insert tail result #{DB}) | 
#{30EF} (insert tail result #{DC}) | 
#{30F3} (insert tail result #{DD}) | 
#{309B} (insert tail result #{DE}) | 
#{309C} (insert tail result #{DF}) | 
#{00} copy c 1 skip (insert tail result c) | 
copy c 2 skip (decodeUnknownChar c)
]