; MACINTOSH UCS-2 encoding rule
; source:  ftp://dkuug.dk/i18n/charmaps/MACINTOSH
any [
#{80} (insert tail result #{00C4}) | 
#{81} (insert tail result #{00C5}) | 
#{82} (insert tail result #{00C7}) | 
#{83} (insert tail result #{00C9}) | 
#{84} (insert tail result #{00D1}) | 
#{85} (insert tail result #{00D6}) | 
#{86} (insert tail result #{00DC}) | 
#{87} (insert tail result #{00E1}) | 
#{88} (insert tail result #{00E0}) | 
#{89} (insert tail result #{00E2}) | 
#{8A} (insert tail result #{00E4}) | 
#{8B} (insert tail result #{00E3}) | 
#{8C} (insert tail result #{00E5}) | 
#{8D} (insert tail result #{00E7}) | 
#{8E} (insert tail result #{00E9}) | 
#{8F} (insert tail result #{00E8}) | 
#{90} (insert tail result #{00EA}) | 
#{91} (insert tail result #{00EB}) | 
#{92} (insert tail result #{00ED}) | 
#{93} (insert tail result #{00EC}) | 
#{94} (insert tail result #{00EE}) | 
#{95} (insert tail result #{00EF}) | 
#{96} (insert tail result #{00F1}) | 
#{97} (insert tail result #{00F3}) | 
#{98} (insert tail result #{00F2}) | 
#{99} (insert tail result #{00F4}) | 
#{9A} (insert tail result #{00F6}) | 
#{9B} (insert tail result #{00F5}) | 
#{9C} (insert tail result #{00FA}) | 
#{9D} (insert tail result #{00F9}) | 
#{9E} (insert tail result #{00FB}) | 
#{9F} (insert tail result #{00FC}) | 
#{A0} (insert tail result #{2020}) | 
#{A1} (insert tail result #{00B0}) | 
#{A4} (insert tail result #{00A7}) | 
#{A5} (insert tail result #{2022}) | 
#{A6} (insert tail result #{00B6}) | 
#{A7} (insert tail result #{00DF}) | 
#{A8} (insert tail result #{00AE}) | 
#{AA} (insert tail result #{2122}) | 
#{AB} (insert tail result #{00B4}) | 
#{AC} (insert tail result #{00A8}) | 
#{AD} (insert tail result #{2260}) | 
#{AE} (insert tail result #{00C6}) | 
#{AF} (insert tail result #{00D8}) | 
#{B0} (insert tail result #{221E}) | 
#{B2} (insert tail result #{2264}) | 
#{B3} (insert tail result #{2265}) | 
#{B4} (insert tail result #{00A5}) | 
#{B6} (insert tail result #{2202}) | 
#{B7} (insert tail result #{2211}) | 
#{B8} (insert tail result #{220F}) | 
#{B9} (insert tail result #{03C0}) | 
#{BA} (insert tail result #{222B}) | 
#{BB} (insert tail result #{00AA}) | 
#{BC} (insert tail result #{00BA}) | 
#{BD} (insert tail result #{03A9}) | 
#{BE} (insert tail result #{00E6}) | 
#{BF} (insert tail result #{00F8}) | 
#{C0} (insert tail result #{00BF}) | 
#{C1} (insert tail result #{00A1}) | 
#{C2} (insert tail result #{00AC}) | 
#{C3} (insert tail result #{221A}) | 
#{C4} (insert tail result #{0192}) | 
#{C5} (insert tail result #{2248}) | 
#{C6} (insert tail result #{0394}) | 
#{C7} (insert tail result #{00AB}) | 
#{C8} (insert tail result #{00BB}) | 
#{C9} (insert tail result #{2026}) | 
#{CA} (insert tail result #{00A0}) | 
#{CB} (insert tail result #{00C0}) | 
#{CC} (insert tail result #{00C3}) | 
#{CD} (insert tail result #{2126}) | 
#{CE} (insert tail result #{0152}) | 
#{CF} (insert tail result #{0153}) | 
#{D0} (insert tail result #{2013}) | 
#{D1} (insert tail result #{2014}) | 
#{D2} (insert tail result #{201C}) | 
#{D3} (insert tail result #{201D}) | 
#{D4} (insert tail result #{2018}) | 
#{D5} (insert tail result #{2019}) | 
#{D6} (insert tail result #{00F7}) | 
#{D7} (insert tail result #{25CA}) | 
#{D8} (insert tail result #{00FF}) | 
#{D9} (insert tail result #{0178}) | 
#{DA} (insert tail result #{2044}) | 
#{DB} (insert tail result #{00A4}) | 
#{DC} (insert tail result #{2039}) | 
#{DD} (insert tail result #{203A}) | 
#{DE} (insert tail result #{FB01}) | 
#{DF} (insert tail result #{FB02}) | 
#{E0} (insert tail result #{2021}) | 
#{E1} (insert tail result #{00B7}) | 
#{E2} (insert tail result #{201A}) | 
#{E3} (insert tail result #{201E}) | 
#{E4} (insert tail result #{2030}) | 
#{E5} (insert tail result #{00C2}) | 
#{E6} (insert tail result #{00CA}) | 
#{E7} (insert tail result #{00C1}) | 
#{E8} (insert tail result #{00CB}) | 
#{E9} (insert tail result #{00C8}) | 
#{EA} (insert tail result #{00CD}) | 
#{EB} (insert tail result #{00CE}) | 
#{EC} (insert tail result #{00CF}) | 
#{ED} (insert tail result #{00CC}) | 
#{EE} (insert tail result #{00D3}) | 
#{EF} (insert tail result #{00D4}) | 
#{F0} (insert tail result #{E01E}) | 
#{F1} (insert tail result #{00D2}) | 
#{F2} (insert tail result #{00DA}) | 
#{F3} (insert tail result #{00DB}) | 
#{F4} (insert tail result #{00D9}) | 
#{F5} (insert tail result #{0131}) | 
#{F8} (insert tail result #{00AF}) | 
#{F9} (insert tail result #{02D8}) | 
#{FA} (insert tail result #{02D9}) | 
#{FB} (insert tail result #{02DA}) | 
#{FC} (insert tail result #{00B8}) | 
#{FD} (insert tail result #{02DD}) | 
#{FE} (insert tail result #{02DB}) | 
#{FF} (insert tail result #{02C7}) | 
copy c 1 skip (insert tail result join #{00} c)
]