; NEXTSTEP UCS-2 decoding rule
;  source: ftp://dkuug.dk/i18n/charmaps/NEXTSTEP
any [
#{00A0} (insert tail result #{80}) | 
#{00C0} (insert tail result #{81}) | 
#{00C1} (insert tail result #{82}) | 
#{00C2} (insert tail result #{83}) | 
#{00C3} (insert tail result #{84}) | 
#{00C4} (insert tail result #{85}) | 
#{00C5} (insert tail result #{86}) | 
#{00C7} (insert tail result #{87}) | 
#{00C8} (insert tail result #{88}) | 
#{00C9} (insert tail result #{89}) | 
#{00CA} (insert tail result #{8A}) | 
#{00CB} (insert tail result #{8B}) | 
#{00CC} (insert tail result #{8C}) | 
#{00CD} (insert tail result #{8D}) | 
#{00CE} (insert tail result #{8E}) | 
#{00CF} (insert tail result #{8F}) | 
#{00D0} (insert tail result #{90}) | 
#{00D1} (insert tail result #{91}) | 
#{00D2} (insert tail result #{92}) | 
#{00D3} (insert tail result #{93}) | 
#{00D4} (insert tail result #{94}) | 
#{00D5} (insert tail result #{95}) | 
#{00D6} (insert tail result #{96}) | 
#{00D9} (insert tail result #{97}) | 
#{00DA} (insert tail result #{98}) | 
#{00DB} (insert tail result #{99}) | 
#{00DC} (insert tail result #{9A}) | 
#{00DD} (insert tail result #{9B}) | 
#{00DE} (insert tail result #{9C}) | 
#{00B5} (insert tail result #{9D}) | 
#{00D7} (insert tail result #{9E}) | 
#{00F7} (insert tail result #{9F}) | 
#{00A9} (insert tail result #{A0}) | 
#{2044} (insert tail result #{A4}) | 
#{0192} (insert tail result #{A6}) | 
#{00A4} (insert tail result #{A8}) | 
#{201C} (insert tail result #{AA}) | 
#{FB01} (insert tail result #{AE}) | 
#{FB02} (insert tail result #{AF}) | 
#{00AE} (insert tail result #{B0}) | 
#{2013} (insert tail result #{B1}) | 
#{2020} (insert tail result #{B2}) | 
#{2021} (insert tail result #{B3}) | 
#{00B7} (insert tail result #{B4}) | 
#{00A6} (insert tail result #{B5}) | 
#{2022} (insert tail result #{B7}) | 
#{201D} (insert tail result #{BA}) | 
#{2026} (insert tail result #{BC}) | 
#{2030} (insert tail result #{BD}) | 
#{00AC} (insert tail result #{BE}) | 
#{00B9} (insert tail result #{C0}) | 
#{02CB} (insert tail result #{C1}) | 
#{00B4} (insert tail result #{C2}) | 
#{02C6} (insert tail result #{C3}) | 
#{02DC} (insert tail result #{C4}) | 
#{00AF} (insert tail result #{C5}) | 
#{02D8} (insert tail result #{C6}) | 
#{02D9} (insert tail result #{C7}) | 
#{00A8} (insert tail result #{C8}) | 
#{00B2} (insert tail result #{C9}) | 
#{02DA} (insert tail result #{CA}) | 
#{00B8} (insert tail result #{CB}) | 
#{00B3} (insert tail result #{CC}) | 
#{02DD} (insert tail result #{CD}) | 
#{02DB} (insert tail result #{CE}) | 
#{02C7} (insert tail result #{CF}) | 
#{2014} (insert tail result #{D0}) | 
#{00B1} (insert tail result #{D1}) | 
#{00BC} (insert tail result #{D2}) | 
#{00BD} (insert tail result #{D3}) | 
#{00BE} (insert tail result #{D4}) | 
#{00E0} (insert tail result #{D5}) | 
#{00E1} (insert tail result #{D6}) | 
#{00E2} (insert tail result #{D7}) | 
#{00E3} (insert tail result #{D8}) | 
#{00E4} (insert tail result #{D9}) | 
#{00E5} (insert tail result #{DA}) | 
#{00E7} (insert tail result #{DB}) | 
#{00E8} (insert tail result #{DC}) | 
#{00E9} (insert tail result #{DD}) | 
#{00EA} (insert tail result #{DE}) | 
#{00EB} (insert tail result #{DF}) | 
#{00EC} (insert tail result #{E0}) | 
#{00C6} (insert tail result #{E1}) | 
#{00ED} (insert tail result #{E2}) | 
#{00AA} (insert tail result #{E3}) | 
#{00EE} (insert tail result #{E4}) | 
#{00EF} (insert tail result #{E5}) | 
#{00F0} (insert tail result #{E6}) | 
#{00F1} (insert tail result #{E7}) | 
#{0141} (insert tail result #{E8}) | 
#{00D8} (insert tail result #{E9}) | 
#{0152} (insert tail result #{EA}) | 
#{00BA} (insert tail result #{EB}) | 
#{00F2} (insert tail result #{EC}) | 
#{00F3} (insert tail result #{ED}) | 
#{00F4} (insert tail result #{EE}) | 
#{00F5} (insert tail result #{EF}) | 
#{00F6} (insert tail result #{F0}) | 
#{00E6} (insert tail result #{F1}) | 
#{00F9} (insert tail result #{F2}) | 
#{00FA} (insert tail result #{F3}) | 
#{00FB} (insert tail result #{F4}) | 
#{0131} (insert tail result #{F5}) | 
#{00FC} (insert tail result #{F6}) | 
#{00FD} (insert tail result #{F7}) | 
#{0142} (insert tail result #{F8}) | 
#{00F8} (insert tail result #{F9}) | 
#{0153} (insert tail result #{FA}) | 
#{00DF} (insert tail result #{FB}) | 
#{00FE} (insert tail result #{FC}) | 
#{00FF} (insert tail result #{FD}) | 
#{00} copy c 1 skip (insert tail result c) | 
copy c 2 skip (decodeUnknownChar c)
]