; CP1250 to UTF8 encoding rule
any [
copy c 1 ASCII (insert tail result c) |
#{80} (insert tail result #{C280}) |
#{81} (insert tail result #{C281}) |
#{82} (insert tail result #{E2809A}) |
#{83} (insert tail result #{C283}) |
#{84} (insert tail result #{E2809E}) |
#{85} (insert tail result #{E280A6}) |
#{86} (insert tail result #{E280A0}) |
#{87} (insert tail result #{E280A1}) |
#{88} (insert tail result #{C288}) |
#{89} (insert tail result #{E280B0}) |
#{8A} (insert tail result #{C5A0}) |
#{8B} (insert tail result #{E280B9}) |
#{8C} (insert tail result #{C59A}) |
#{8D} (insert tail result #{C5A4}) |
#{8E} (insert tail result #{C5BD}) |
#{8F} (insert tail result #{C5B9}) |
#{90} (insert tail result #{C290}) |
#{91} (insert tail result #{E28098}) |
#{92} (insert tail result #{E28099}) |
#{93} (insert tail result #{E2809C}) |
#{94} (insert tail result #{E2809D}) |
#{95} (insert tail result #{E280A2}) |
#{96} (insert tail result #{E28093}) |
#{97} (insert tail result #{E28094}) |
#{98} (insert tail result #{C298}) |
#{99} (insert tail result #{E284A2}) |
#{9A} (insert tail result #{C5A1}) |
#{9B} (insert tail result #{E280BA}) |
#{9C} (insert tail result #{C59B}) |
#{9D} (insert tail result #{C5A5}) |
#{9E} (insert tail result #{C5BE}) |
#{9F} (insert tail result #{C5BA}) |
#{A0} (insert tail result #{C2A0}) |
#{A1} (insert tail result #{CB87}) |
#{A2} (insert tail result #{CB98}) |
#{A3} (insert tail result #{C581}) |
#{A4} (insert tail result #{C2A4}) |
#{A5} (insert tail result #{C484}) |
#{A6} (insert tail result #{C2A6}) |
#{A7} (insert tail result #{C2A7}) |
#{A8} (insert tail result #{C2A8}) |
#{A9} (insert tail result #{C2A9}) |
#{AA} (insert tail result #{C59E}) |
#{AB} (insert tail result #{C2AB}) |
#{AC} (insert tail result #{C2AC}) |
#{AD} (insert tail result #{C2AD}) |
#{AE} (insert tail result #{C2AE}) |
#{AF} (insert tail result #{C5BB}) |
#{B0} (insert tail result #{C2B0}) |
#{B1} (insert tail result #{C2B1}) |
#{B2} (insert tail result #{CB9B}) |
#{B3} (insert tail result #{C582}) |
#{B4} (insert tail result #{C2B4}) |
#{B5} (insert tail result #{C2B5}) |
#{B6} (insert tail result #{C2B6}) |
#{B7} (insert tail result #{C2B7}) |
#{B8} (insert tail result #{C2B8}) |
#{B9} (insert tail result #{C485}) |
#{BA} (insert tail result #{C59F}) |
#{BB} (insert tail result #{C2BB}) |
#{BC} (insert tail result #{C4BD}) |
#{BD} (insert tail result #{CB9D}) |
#{BE} (insert tail result #{C4BE}) |
#{BF} (insert tail result #{C5BC}) |
#{C0} (insert tail result #{C594}) |
#{C1} (insert tail result #{C381}) |
#{C2} (insert tail result #{C382}) |
#{C3} (insert tail result #{C482}) |
#{C4} (insert tail result #{C384}) |
#{C5} (insert tail result #{C4B9}) |
#{C6} (insert tail result #{C486}) |
#{C7} (insert tail result #{C387}) |
#{C8} (insert tail result #{C48C}) |
#{C9} (insert tail result #{C389}) |
#{CA} (insert tail result #{C498}) |
#{CB} (insert tail result #{C38B}) |
#{CC} (insert tail result #{C49A}) |
#{CD} (insert tail result #{C38D}) |
#{CE} (insert tail result #{C38E}) |
#{CF} (insert tail result #{C48E}) |
#{D0} (insert tail result #{C490}) |
#{D1} (insert tail result #{C583}) |
#{D2} (insert tail result #{C587}) |
#{D3} (insert tail result #{C393}) |
#{D4} (insert tail result #{C394}) |
#{D5} (insert tail result #{C590}) |
#{D6} (insert tail result #{C396}) |
#{D7} (insert tail result #{C397}) |
#{D8} (insert tail result #{C598}) |
#{D9} (insert tail result #{C5AE}) |
#{DA} (insert tail result #{C39A}) |
#{DB} (insert tail result #{C5B0}) |
#{DC} (insert tail result #{C39C}) |
#{DD} (insert tail result #{C39D}) |
#{DE} (insert tail result #{C5A2}) |
#{DF} (insert tail result #{C39F}) |
#{E0} (insert tail result #{C595}) |
#{E1} (insert tail result #{C3A1}) |
#{E2} (insert tail result #{C3A2}) |
#{E3} (insert tail result #{C483}) |
#{E4} (insert tail result #{C3A4}) |
#{E5} (insert tail result #{C4BA}) |
#{E6} (insert tail result #{C487}) |
#{E7} (insert tail result #{C3A7}) |
#{E8} (insert tail result #{C48D}) |
#{E9} (insert tail result #{C3A9}) |
#{EA} (insert tail result #{C499}) |
#{EB} (insert tail result #{C3AB}) |
#{EC} (insert tail result #{C49B}) |
#{ED} (insert tail result #{C3AD}) |
#{EE} (insert tail result #{C3AE}) |
#{EF} (insert tail result #{C48F}) |
#{F0} (insert tail result #{C491}) |
#{F1} (insert tail result #{C584}) |
#{F2} (insert tail result #{C588}) |
#{F3} (insert tail result #{C3B3}) |
#{F4} (insert tail result #{C3B4}) |
#{F5} (insert tail result #{C591}) |
#{F6} (insert tail result #{C3B6}) |
#{F7} (insert tail result #{C3B7}) |
#{F8} (insert tail result #{C599}) |
#{F9} (insert tail result #{C5AF}) |
#{FA} (insert tail result #{C3BA}) |
#{FB} (insert tail result #{C5B1}) |
#{FC} (insert tail result #{C3BC}) |
#{FD} (insert tail result #{C3BD}) |
#{FE} (insert tail result #{C5A3}) |
#{FF} (insert tail result #{CB99}) |


copy c 1 skip (print ["unknown" mold c])
]