; UTF8 to CP1250 decoding rule
any [
copy c 1 ASCII (insert tail result c) | 
#{C280} (insert tail result #{80}) |
#{C281} (insert tail result #{81}) |
#{E2809A} (insert tail result #{82}) |
#{C283} (insert tail result #{83}) |
#{E2809E} (insert tail result #{84}) |
#{E280A6} (insert tail result #{85}) |
#{E280A0} (insert tail result #{86}) |
#{E280A1} (insert tail result #{87}) |
#{C288} (insert tail result #{88}) |
#{E280B0} (insert tail result #{89}) |
#{C5A0} (insert tail result #{8A}) |
#{E280B9} (insert tail result #{8B}) |
#{C59A} (insert tail result #{8C}) |
#{C5A4} (insert tail result #{8D}) |
#{C5BD} (insert tail result #{8E}) |
#{C5B9} (insert tail result #{8F}) |
#{C290} (insert tail result #{90}) |
#{E28098} (insert tail result #{91}) |
#{E28099} (insert tail result #{92}) |
#{E2809C} (insert tail result #{93}) |
#{E2809D} (insert tail result #{94}) |
#{E280A2} (insert tail result #{95}) |
#{E28093} (insert tail result #{96}) |
#{E28094} (insert tail result #{97}) |
#{C298} (insert tail result #{98}) |
#{E284A2} (insert tail result #{99}) |
#{C5A1} (insert tail result #{9A}) |
#{E280BA} (insert tail result #{9B}) |
#{C59B} (insert tail result #{9C}) |
#{C5A5} (insert tail result #{9D}) |
#{C5BE} (insert tail result #{9E}) |
#{C5BA} (insert tail result #{9F}) |
#{C2A0} (insert tail result #{A0}) |
#{CB87} (insert tail result #{A1}) |
#{CB98} (insert tail result #{A2}) |
#{C581} (insert tail result #{A3}) |
#{C2A4} (insert tail result #{A4}) |
#{C484} (insert tail result #{A5}) |
#{C2A6} (insert tail result #{A6}) |
#{C2A7} (insert tail result #{A7}) |
#{C2A8} (insert tail result #{A8}) |
#{C2A9} (insert tail result #{A9}) |
#{C59E} (insert tail result #{AA}) |
#{C2AB} (insert tail result #{AB}) |
#{C2AC} (insert tail result #{AC}) |
#{C2AD} (insert tail result #{AD}) |
#{C2AE} (insert tail result #{AE}) |
#{C5BB} (insert tail result #{AF}) |
#{C2B0} (insert tail result #{B0}) |
#{C2B1} (insert tail result #{B1}) |
#{CB9B} (insert tail result #{B2}) |
#{C582} (insert tail result #{B3}) |
#{C2B4} (insert tail result #{B4}) |
#{C2B5} (insert tail result #{B5}) |
#{C2B6} (insert tail result #{B6}) |
#{C2B7} (insert tail result #{B7}) |
#{C2B8} (insert tail result #{B8}) |
#{C485} (insert tail result #{B9}) |
#{C59F} (insert tail result #{BA}) |
#{C2BB} (insert tail result #{BB}) |
#{C4BD} (insert tail result #{BC}) |
#{CB9D} (insert tail result #{BD}) |
#{C4BE} (insert tail result #{BE}) |
#{C5BC} (insert tail result #{BF}) |
#{C594} (insert tail result #{C0}) |
#{C381} (insert tail result #{C1}) |
#{C382} (insert tail result #{C2}) |
#{C482} (insert tail result #{C3}) |
#{C384} (insert tail result #{C4}) |
#{C4B9} (insert tail result #{C5}) |
#{C486} (insert tail result #{C6}) |
#{C387} (insert tail result #{C7}) |
#{C48C} (insert tail result #{C8}) |
#{C389} (insert tail result #{C9}) |
#{C498} (insert tail result #{CA}) |
#{C38B} (insert tail result #{CB}) |
#{C49A} (insert tail result #{CC}) |
#{C38D} (insert tail result #{CD}) |
#{C38E} (insert tail result #{CE}) |
#{C48E} (insert tail result #{CF}) |
#{C490} (insert tail result #{D0}) |
#{C583} (insert tail result #{D1}) |
#{C587} (insert tail result #{D2}) |
#{C393} (insert tail result #{D3}) |
#{C394} (insert tail result #{D4}) |
#{C590} (insert tail result #{D5}) |
#{C396} (insert tail result #{D6}) |
#{C397} (insert tail result #{D7}) |
#{C598} (insert tail result #{D8}) |
#{C5AE} (insert tail result #{D9}) |
#{C39A} (insert tail result #{DA}) |
#{C5B0} (insert tail result #{DB}) |
#{C39C} (insert tail result #{DC}) |
#{C39D} (insert tail result #{DD}) |
#{C5A2} (insert tail result #{DE}) |
#{C39F} (insert tail result #{DF}) |
#{C595} (insert tail result #{E0}) |
#{C3A1} (insert tail result #{E1}) |
#{C3A2} (insert tail result #{E2}) |
#{C483} (insert tail result #{E3}) |
#{C3A4} (insert tail result #{E4}) |
#{C4BA} (insert tail result #{E5}) |
#{C487} (insert tail result #{E6}) |
#{C3A7} (insert tail result #{E7}) |
#{C48D} (insert tail result #{E8}) |
#{C3A9} (insert tail result #{E9}) |
#{C499} (insert tail result #{EA}) |
#{C3AB} (insert tail result #{EB}) |
#{C49B} (insert tail result #{EC}) |
#{C3AD} (insert tail result #{ED}) |
#{C3AE} (insert tail result #{EE}) |
#{C48F} (insert tail result #{EF}) |
#{C491} (insert tail result #{F0}) |
#{C584} (insert tail result #{F1}) |
#{C588} (insert tail result #{F2}) |
#{C3B3} (insert tail result #{F3}) |
#{C3B4} (insert tail result #{F4}) |
#{C591} (insert tail result #{F5}) |
#{C3B6} (insert tail result #{F6}) |
#{C3B7} (insert tail result #{F7}) |
#{C599} (insert tail result #{F8}) |
#{C5AF} (insert tail result #{F9}) |
#{C3BA} (insert tail result #{FA}) |
#{C5B1} (insert tail result #{FB}) |
#{C3BC} (insert tail result #{FC}) |
#{C3BD} (insert tail result #{FD}) |
#{C5A3} (insert tail result #{FE}) |
#{CB99} (insert tail result #{FF}) |
#{C3A8} (insert tail result #{65}) |
copy c 2 skip (print ["unknown" mold c])
]