
"/DOMDocument" 
"/DOMDocument/media" 
"/DOMDocument/media/DOMBitmapItem" 
"/DOMDocument/media/DOMSoundItem" 
"/DOMDocument/symbols" 
"/DOMDocument/symbols/Include" 
"/DOMDocument/timelines" 
"/DOMDocument/timelines/DOMTimeline" 
"/DOMDocument/timelines/DOMTimeline/layers" 
"/DOMDocument/timelines/DOMTimeline/layers/DOMLayer" 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/Actionscript} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/Actionscript/script} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/SolidColor} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/edges} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/edges/Edge} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/transformationPoint} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/transformationPoint/Point} 
"/DOMDocument/swatchLists" 
"/DOMDocument/swatchLists/swatchList" 
"/DOMDocument/swatchLists/swatchList/swatches" 
{/DOMDocument/swatchLists/swatchList/swatches/SolidSwatchItem} 
"/DOMDocument/extendedSwatchLists" 
"/DOMDocument/extendedSwatchLists/swatchList" 
{/DOMDocument/extendedSwatchLists/swatchList/swatches} 
{/DOMDocument/extendedSwatchLists/swatchList/swatches/LinearGradientSwatchItem} 
{/DOMDocument/extendedSwatchLists/swatchList/swatches/LinearGradientSwatchItem/GradientEntry} 
{/DOMDocument/extendedSwatchLists/swatchList/swatches/RadialGradientSwatchItem} 
{/DOMDocument/extendedSwatchLists/swatchList/swatches/RadialGradientSwatchItem/GradientEntry} 
"/DOMDocument/PrinterSettings" 
"/DOMDocument/publishHistory" 
"/DOMDocument/publishHistory/PublishItem" 
"/DOMSymbolItem" 
"/DOMSymbolItem/timeline" 
"/DOMSymbolItem/timeline/DOMTimeline" 
"/DOMSymbolItem/timeline/DOMTimeline/layers" 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/color} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/color/Color} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/tweens} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/tweens/CustomEase} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/tweens/CustomEase/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/edges} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/edges/Edge} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient/GradientEntry} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/Actionscript} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/Actionscript/script} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/BitmapFill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/BitmapFill/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/BitmapFill/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/filters} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/filters/BlurFilter} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/SoundEnvelope} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/SoundEnvelope/SoundEnvelopePoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/Actionscript} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/Actionscript/script} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/MorphShape} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/MorphShape/morphSegments} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/MorphShape/morphSegments/MorphSegment} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/MorphShape/morphSegments/MorphSegment/MorphCurves} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/MorphShape/morphHintsList} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/RadialGradient} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/RadialGradient/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/RadialGradient/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/RadialGradient/GradientEntry} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/edges} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/edges/Edge} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient/GradientEntry} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/filters/GlowFilter} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/BitmapFill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/BitmapFill/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/BitmapFill/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/SoundEnvelope} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/SoundEnvelope/SoundEnvelopePoint} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/transformationPoint} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/transformationPoint/Point} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/SolidColor} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/edges} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/edges/Edge} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/BitmapFill} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/BitmapFill/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/BitmapFill/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/color} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/color/Color} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/BitmapFill} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/BitmapFill/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/BitmapFill/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/RadialGradient/GradientEntry} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/StippleStroke} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/StippleStroke/fill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/StippleStroke/fill/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/SolidColor} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/filters} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/filters/BlurFilter} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/transformationPoint} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/transformationPoint/Point} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/fills} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle/SolidColor} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/edges} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/edges/Edge} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/Actionscript} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/Actionscript/script} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/SolidColor} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/tweens} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/tweens/CustomEase} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/tweens/CustomEase/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/morphHintsList} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/morphHintsList/MorphHint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/fills} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/edges} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/edges/Edge} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/strokes} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/strokes/StrokeStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/strokes/StrokeStyle/SolidStroke} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/strokes/StrokeStyle/SolidStroke/fill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/strokes/StrokeStyle/SolidStroke/fill/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/fills} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/edges} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/edges/Edge} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMShape/matrix/Matrix} 
"/DOMDocument/folders" 
"/DOMDocument/folders/DOMFolderItem" 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/strokes} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/strokes/StrokeStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/strokes/StrokeStyle/SolidStroke} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/strokes/StrokeStyle/SolidStroke/fill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/strokes/StrokeStyle/SolidStroke/fill/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMSymbolInstance/filters/DropShadowFilter} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMBitmapInstance} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/DottedStroke} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/DottedStroke/fill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/DottedStroke/fill/SolidColor} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/transformationPoint} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMBitmapInstance/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/members} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/fills} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/fills/FillStyle/SolidColor} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/edges} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMShape/edges/Edge} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMGroup/members/DOMGroup/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/transformationPoint} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/transformationPoint/Point} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/color} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/color/Color} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMSymbolInstance} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMSymbolInstance/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMSymbolInstance/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMSymbolInstance/transformationPoint} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMGroup/members/DOMSymbolInstance/transformationPoint/Point} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/RadialGradient} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/RadialGradient/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/RadialGradient/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/RadialGradient/GradientEntry} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/color} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMSymbolInstance/color/Color} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/LinearGradient} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/LinearGradient/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/LinearGradient/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/SolidStroke/fill/LinearGradient/GradientEntry} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText/textRuns} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText/textRuns/DOMTextRun} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText/textRuns/DOMTextRun/characters} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText/textRuns/DOMTextRun/textAttrs} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMDynamicText/textRuns/DOMTextRun/textAttrs/DOMTextAttrs} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/RaggedStroke} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/RaggedStroke/fill} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/strokes/StrokeStyle/RaggedStroke/fill/SolidColor} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient/matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient/matrix/Matrix} 
{/DOMDocument/timelines/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMShape/fills/FillStyle/LinearGradient/GradientEntry} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/LinearGradient} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/LinearGradient/matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/LinearGradient/matrix/Matrix} 
{/DOMSymbolItem/timeline/DOMTimeline/layers/DOMLayer/frames/DOMFrame/elements/DOMGroup/members/DOMShape/fills/FillStyle/LinearGradient/GradientEntry}